In [3]:
import numpy as np

In [4]:
def logisticLoss(y_hat, y):
    return -(y_hat * np.log(y) + (1 - y_hat) * np.log(1 - y))

logisticLoss(0.9, 1)

C:\Users\Sihan Tao\AppData\Local\Temp\ipykernel_25624\3232406275.py:2: RuntimeWarning: divide by zero encountered in log
  return -(y_hat * np.log(y) + (1 - y_hat) * np.log(1 - y))


inf

In [14]:
x = np.random.rand(8, 1)
y = x.reshape(2, 2, 2)
y
y.shape

(2, 2, 2)

In [10]:
a = np.random.randn(3, 3)
b = np.random.rand(2, 1)
a + b

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [11]:
x=np.array([[[1],[2]],[[3],[4]]])
x.shape

(2, 2, 1)

In [17]:
a=np.random.randn(4,3)

b = np.random.randn(3, 2)

c = np.dot(a, b)

In [18]:
a = np.array([[2, 1], [1, 3]])
a * a

array([[4, 1],
       [1, 9]])

In [26]:
a = np.random.randn(3, 3)
a

array([[ 0.45887228,  0.47117102, -2.06179245],
       [ 1.12700624, -1.01040045,  0.01599995],
       [ 1.41000914, -0.35558369,  0.40257108]])

In [27]:
a ** 2

array([[2.10563771e-01, 2.22002129e-01, 4.25098812e+00],
       [1.27014305e+00, 1.02090906e+00, 2.55998411e-04],
       [1.98812576e+00, 1.26439758e-01, 1.62063478e-01]])